// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test2.Models;

namespace Test2.Migrations
{
    [DbContext(typeof(Ch2CContext))]
    partial class Ch2CContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Test2.Models.ItemsToBuy", b =>
                {
                    b.Property<int>("ItemsToBuyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Guid");

                    b.Property<string>("Name");

                    b.HasKey("ItemsToBuyID");

                    b.ToTable("ItemsToBuys");
                });

            modelBuilder.Entity("Test2.Models.LogLine", b =>
                {
                    b.Property<int>("LogLineID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LogTime");

                    b.Property<string>("Message");

                    b.HasKey("LogLineID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Test2.Models.ResourceRead", b =>
                {
                    b.Property<int>("ResourceReadID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ResourceUUID");

                    b.Property<int>("TeamID");

                    b.HasKey("ResourceReadID");

                    b.ToTable("ResourceReads");
                });

            modelBuilder.Entity("Test2.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cloth");

                    b.Property<int>("Metal");

                    b.Property<int>("NumberOfActions");

                    b.Property<int>("Plastic");

                    b.Property<DateTime>("StarTtime");

                    b.Property<string>("TeamName");

                    b.Property<int>("Wood");

                    b.HasKey("TeamID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Test2.Models.TeamHasBought", b =>
                {
                    b.Property<int>("TeamHasBoughtID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bought");

                    b.Property<int>("TeamID");

                    b.HasKey("TeamHasBoughtID");

                    b.HasIndex("TeamID");

                    b.ToTable("TeamHasBoughts");
                });

            modelBuilder.Entity("Test2.Models.TeamHasBought", b =>
                {
                    b.HasOne("Test2.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
